// flow-typed signature: f1b5aca78b7fd3ee1d52b2d5582549bf
// flow-typed version: <<STUB>>/docxtemplater_v^3.9.5/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docxtemplater'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docxtemplater' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docxtemplater/build/docxtemplater' {
  declare module.exports: any;
}

declare module 'docxtemplater/build/docxtemplater.min' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/browser-versions/fs' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/browser-versions/xmldom' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/doc-utils' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/docxtemplater' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/errors' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/file-type-config' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/inspect-module' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/lexer' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/mergesort' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/module-wrapper' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/modules/expand-pair-trait' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/modules/loop' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/modules/rawxml' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/modules/render' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/modules/space-preserve' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/parser' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/postrender' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/prefix-matcher' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/render' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/resolve' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/scope-manager' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/angular-parser' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/base' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/doc-props' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/errors' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/filenames' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/fixtures' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/index' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/integration' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/lexer-parser-render' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/speed' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/utils' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/xml-matcher' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/xml-prettify' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/tests/xml-templater' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/traits' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/xml-matcher' {
  declare module.exports: any;
}

declare module 'docxtemplater/js/xml-templater' {
  declare module.exports: any;
}

declare module 'docxtemplater/webdriver' {
  declare module.exports: any;
}

declare module 'docxtemplater/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docxtemplater/build/docxtemplater.js' {
  declare module.exports: $Exports<'docxtemplater/build/docxtemplater'>;
}
declare module 'docxtemplater/build/docxtemplater.min.js' {
  declare module.exports: $Exports<'docxtemplater/build/docxtemplater.min'>;
}
declare module 'docxtemplater/js/browser-versions/fs.js' {
  declare module.exports: $Exports<'docxtemplater/js/browser-versions/fs'>;
}
declare module 'docxtemplater/js/browser-versions/xmldom.js' {
  declare module.exports: $Exports<'docxtemplater/js/browser-versions/xmldom'>;
}
declare module 'docxtemplater/js/doc-utils.js' {
  declare module.exports: $Exports<'docxtemplater/js/doc-utils'>;
}
declare module 'docxtemplater/js/docxtemplater.js' {
  declare module.exports: $Exports<'docxtemplater/js/docxtemplater'>;
}
declare module 'docxtemplater/js/errors.js' {
  declare module.exports: $Exports<'docxtemplater/js/errors'>;
}
declare module 'docxtemplater/js/file-type-config.js' {
  declare module.exports: $Exports<'docxtemplater/js/file-type-config'>;
}
declare module 'docxtemplater/js/inspect-module.js' {
  declare module.exports: $Exports<'docxtemplater/js/inspect-module'>;
}
declare module 'docxtemplater/js/lexer.js' {
  declare module.exports: $Exports<'docxtemplater/js/lexer'>;
}
declare module 'docxtemplater/js/mergesort.js' {
  declare module.exports: $Exports<'docxtemplater/js/mergesort'>;
}
declare module 'docxtemplater/js/module-wrapper.js' {
  declare module.exports: $Exports<'docxtemplater/js/module-wrapper'>;
}
declare module 'docxtemplater/js/modules/expand-pair-trait.js' {
  declare module.exports: $Exports<'docxtemplater/js/modules/expand-pair-trait'>;
}
declare module 'docxtemplater/js/modules/loop.js' {
  declare module.exports: $Exports<'docxtemplater/js/modules/loop'>;
}
declare module 'docxtemplater/js/modules/rawxml.js' {
  declare module.exports: $Exports<'docxtemplater/js/modules/rawxml'>;
}
declare module 'docxtemplater/js/modules/render.js' {
  declare module.exports: $Exports<'docxtemplater/js/modules/render'>;
}
declare module 'docxtemplater/js/modules/space-preserve.js' {
  declare module.exports: $Exports<'docxtemplater/js/modules/space-preserve'>;
}
declare module 'docxtemplater/js/parser.js' {
  declare module.exports: $Exports<'docxtemplater/js/parser'>;
}
declare module 'docxtemplater/js/postrender.js' {
  declare module.exports: $Exports<'docxtemplater/js/postrender'>;
}
declare module 'docxtemplater/js/prefix-matcher.js' {
  declare module.exports: $Exports<'docxtemplater/js/prefix-matcher'>;
}
declare module 'docxtemplater/js/render.js' {
  declare module.exports: $Exports<'docxtemplater/js/render'>;
}
declare module 'docxtemplater/js/resolve.js' {
  declare module.exports: $Exports<'docxtemplater/js/resolve'>;
}
declare module 'docxtemplater/js/scope-manager.js' {
  declare module.exports: $Exports<'docxtemplater/js/scope-manager'>;
}
declare module 'docxtemplater/js/tests/angular-parser.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/angular-parser'>;
}
declare module 'docxtemplater/js/tests/base.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/base'>;
}
declare module 'docxtemplater/js/tests/doc-props.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/doc-props'>;
}
declare module 'docxtemplater/js/tests/errors.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/errors'>;
}
declare module 'docxtemplater/js/tests/filenames.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/filenames'>;
}
declare module 'docxtemplater/js/tests/fixtures.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/fixtures'>;
}
declare module 'docxtemplater/js/tests/index.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/index'>;
}
declare module 'docxtemplater/js/tests/integration.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/integration'>;
}
declare module 'docxtemplater/js/tests/lexer-parser-render.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/lexer-parser-render'>;
}
declare module 'docxtemplater/js/tests/speed.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/speed'>;
}
declare module 'docxtemplater/js/tests/utils.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/utils'>;
}
declare module 'docxtemplater/js/tests/xml-matcher.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/xml-matcher'>;
}
declare module 'docxtemplater/js/tests/xml-prettify.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/xml-prettify'>;
}
declare module 'docxtemplater/js/tests/xml-templater.js' {
  declare module.exports: $Exports<'docxtemplater/js/tests/xml-templater'>;
}
declare module 'docxtemplater/js/traits.js' {
  declare module.exports: $Exports<'docxtemplater/js/traits'>;
}
declare module 'docxtemplater/js/xml-matcher.js' {
  declare module.exports: $Exports<'docxtemplater/js/xml-matcher'>;
}
declare module 'docxtemplater/js/xml-templater.js' {
  declare module.exports: $Exports<'docxtemplater/js/xml-templater'>;
}
declare module 'docxtemplater/webdriver.js' {
  declare module.exports: $Exports<'docxtemplater/webdriver'>;
}
declare module 'docxtemplater/webpack.config.js' {
  declare module.exports: $Exports<'docxtemplater/webpack.config'>;
}
