// flow-typed signature: 7c5fbd1312f8dbab6e242de091bc9fad
// flow-typed version: <<STUB>>/jszip-utils_v0.0.2/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jszip-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jszip-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jszip-utils/dist/jszip-utils-ie' {
  declare module.exports: any;
}

declare module 'jszip-utils/dist/jszip-utils-ie.min' {
  declare module.exports: any;
}

declare module 'jszip-utils/dist/jszip-utils' {
  declare module.exports: any;
}

declare module 'jszip-utils/dist/jszip-utils.min' {
  declare module.exports: any;
}

declare module 'jszip-utils/Gruntfile' {
  declare module.exports: any;
}

declare module 'jszip-utils/lib/index_IE' {
  declare module.exports: any;
}

declare module 'jszip-utils/lib/index' {
  declare module.exports: any;
}

declare module 'jszip-utils/lib/license_header' {
  declare module.exports: any;
}

declare module 'jszip-utils/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jszip-utils/dist/jszip-utils-ie.js' {
  declare module.exports: $Exports<'jszip-utils/dist/jszip-utils-ie'>;
}
declare module 'jszip-utils/dist/jszip-utils-ie.min.js' {
  declare module.exports: $Exports<'jszip-utils/dist/jszip-utils-ie.min'>;
}
declare module 'jszip-utils/dist/jszip-utils.js' {
  declare module.exports: $Exports<'jszip-utils/dist/jszip-utils'>;
}
declare module 'jszip-utils/dist/jszip-utils.min.js' {
  declare module.exports: $Exports<'jszip-utils/dist/jszip-utils.min'>;
}
declare module 'jszip-utils/Gruntfile.js' {
  declare module.exports: $Exports<'jszip-utils/Gruntfile'>;
}
declare module 'jszip-utils/lib/index_IE.js' {
  declare module.exports: $Exports<'jszip-utils/lib/index_IE'>;
}
declare module 'jszip-utils/lib/index.js' {
  declare module.exports: $Exports<'jszip-utils/lib/index'>;
}
declare module 'jszip-utils/lib/license_header.js' {
  declare module.exports: $Exports<'jszip-utils/lib/license_header'>;
}
declare module 'jszip-utils/test/test.js' {
  declare module.exports: $Exports<'jszip-utils/test/test'>;
}
